openapi: 3.0.3
info:
  title: Users Specification
  description: |-
    To add, update, read, delete users:
    - add user
    - update user
    - delete user
    - read user
  version: 1.0-SNAPSHOT
servers:
  - url: localhost:8080/v1/api
tags:
  - name: Users
    description: Users
paths:
  /user/{userId}:
    get:
      summary: Get user information
      description: Get user information using id
      operationId: getUser
      parameters:
        - name: userId
          in: path
          description: ID of user
          required: true
          schema:
            type: number
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        404:
          description: Account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserNotFoundError'
  /user:
    post:
      summary: Save user information
      description: Save user information using user object
      operationId: saveUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        404:
          description: Account not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserNotFoundError'
components:
  schemas:
    User:
      type: object
      properties:
        firstname:
          type: string
        lastname:
          type: string
        password:
          type: string
        id:
          type: integer
          format: int64
    UserNotFoundError:
      type: object
      properties:
        message:
          type: string